version: "3.1"
services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "postgres-db:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
      POSTGRES_DB: Ecommerce_App
volumes:
  postgres-db:
